sudo: required

language: cpp

branches:
  only: master

matrix:
  include:
    - env: COMPILER=g++-4.8
    - env: COMPILER=g++-5
    - env: COMPILER=clang++-3.5

before_install:
  # Somewhat of a hack to use trusty sources.
  - sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/trusty.list
  - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list.d/trusty.list
  - if [[ $COMPILER == g++-5       ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - sudo apt-get update -qq -y
  - if [[ $COMPILER == g++-4.8     ]]; then sudo apt-get install -q -y g++-4.8;     fi
  - if [[ $COMPILER == g++-5       ]]; then sudo apt-get install -q -y g++-5;       fi
  - if [[ $COMPILER == clang++-3.5 ]]; then sudo apt-get install -q -y clang++-3.5; fi
  - sudo apt-get install -q -y cmake libyaml-cpp-dev libboost-dev

install:
  - cmake --version
  - CXX=$COMPILER cmake .
  - make

script:
  - ./run_tests
